// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/login.proto

package login

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LogInRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogInRequest) Reset()         { *m = LogInRequest{} }
func (m *LogInRequest) String() string { return proto.CompactTextString(m) }
func (*LogInRequest) ProtoMessage()    {}
func (*LogInRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_login_ff1919d717dc979e, []int{0}
}
func (m *LogInRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogInRequest.Unmarshal(m, b)
}
func (m *LogInRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogInRequest.Marshal(b, m, deterministic)
}
func (dst *LogInRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogInRequest.Merge(dst, src)
}
func (m *LogInRequest) XXX_Size() int {
	return xxx_messageInfo_LogInRequest.Size(m)
}
func (m *LogInRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogInRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogInRequest proto.InternalMessageInfo

func (m *LogInRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LogInRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LogInResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogInResponse) Reset()         { *m = LogInResponse{} }
func (m *LogInResponse) String() string { return proto.CompactTextString(m) }
func (*LogInResponse) ProtoMessage()    {}
func (*LogInResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_login_ff1919d717dc979e, []int{1}
}
func (m *LogInResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogInResponse.Unmarshal(m, b)
}
func (m *LogInResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogInResponse.Marshal(b, m, deterministic)
}
func (dst *LogInResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogInResponse.Merge(dst, src)
}
func (m *LogInResponse) XXX_Size() int {
	return xxx_messageInfo_LogInResponse.Size(m)
}
func (m *LogInResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogInResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogInResponse proto.InternalMessageInfo

func (m *LogInResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RegisterRequest struct {
	ApiKey               string   `protobuf:"bytes,1,opt,name=api_key,json=apiKey" json:"api_key,omitempty"`
	Secret               string   `protobuf:"bytes,2,opt,name=secret" json:"secret,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_login_ff1919d717dc979e, []int{2}
}
func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(dst, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

func (m *RegisterRequest) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *RegisterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type User struct {
	Username             string   `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_login_ff1919d717dc979e, []int{3}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_login_ff1919d717dc979e, []int{4}
}
func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (dst *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(dst, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RegisterResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type LogoutRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_login_ff1919d717dc979e, []int{5}
}
func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (dst *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(dst, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

func (m *LogoutRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *LogoutRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LogoutResponse struct {
	IsLoggedOut          bool     `protobuf:"varint,1,opt,name=is_logged_out,json=isLoggedOut" json:"is_logged_out,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutResponse) Reset()         { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()    {}
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_login_ff1919d717dc979e, []int{6}
}
func (m *LogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResponse.Unmarshal(m, b)
}
func (m *LogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResponse.Marshal(b, m, deterministic)
}
func (dst *LogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResponse.Merge(dst, src)
}
func (m *LogoutResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutResponse.Size(m)
}
func (m *LogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResponse proto.InternalMessageInfo

func (m *LogoutResponse) GetIsLoggedOut() bool {
	if m != nil {
		return m.IsLoggedOut
	}
	return false
}

func init() {
	proto.RegisterType((*LogInRequest)(nil), "login.LogInRequest")
	proto.RegisterType((*LogInResponse)(nil), "login.LogInResponse")
	proto.RegisterType((*RegisterRequest)(nil), "login.RegisterRequest")
	proto.RegisterType((*User)(nil), "login.User")
	proto.RegisterType((*RegisterResponse)(nil), "login.RegisterResponse")
	proto.RegisterType((*LogoutRequest)(nil), "login.LogoutRequest")
	proto.RegisterType((*LogoutResponse)(nil), "login.LogoutResponse")
}

func init() { proto.RegisterFile("proto/login.proto", fileDescriptor_login_ff1919d717dc979e) }

var fileDescriptor_login_ff1919d717dc979e = []byte{
	// 362 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x4f, 0x4b, 0xfb, 0x40,
	0x10, 0x25, 0x6d, 0x93, 0xb6, 0xd3, 0x5f, 0x7f, 0xea, 0x5a, 0xdb, 0x92, 0x8b, 0x12, 0x10, 0x3c,
	0x55, 0xa8, 0x7a, 0x12, 0x3c, 0x78, 0x10, 0x8a, 0x05, 0x21, 0xe8, 0xc5, 0x4b, 0x88, 0x66, 0x08,
	0x4b, 0xdb, 0x6c, 0xdc, 0xdd, 0x20, 0xfd, 0x16, 0x7e, 0x17, 0xbf, 0xa0, 0xec, 0x9f, 0xb4, 0x69,
	0xc4, 0xde, 0xf6, 0xcd, 0xec, 0xbc, 0xf7, 0xf6, 0xed, 0xc0, 0x51, 0xce, 0x99, 0x64, 0x97, 0x4b,
	0x96, 0xd2, 0x6c, 0xa2, 0xcf, 0xc4, 0xd5, 0x20, 0x78, 0x80, 0x7f, 0x73, 0x96, 0xce, 0xb2, 0x10,
	0x3f, 0x0a, 0x14, 0x92, 0xf8, 0xd0, 0x29, 0x04, 0xf2, 0x2c, 0x5e, 0xe1, 0xd8, 0x39, 0x73, 0x2e,
	0xba, 0xe1, 0x06, 0xab, 0x5e, 0x1e, 0x0b, 0xf1, 0xc9, 0x78, 0x32, 0x6e, 0x98, 0x5e, 0x89, 0x83,
	0x73, 0xe8, 0x5b, 0x1e, 0x91, 0xb3, 0x4c, 0x20, 0x19, 0x80, 0x2b, 0xd9, 0x02, 0x33, 0xcb, 0x62,
	0x40, 0xf0, 0xe5, 0xc0, 0x41, 0x88, 0x29, 0x15, 0x12, 0x79, 0x29, 0x39, 0x82, 0x76, 0x9c, 0xd3,
	0x68, 0x81, 0x6b, 0x7b, 0xd7, 0x8b, 0x73, 0xfa, 0x88, 0x6b, 0x32, 0x04, 0x4f, 0xe0, 0x3b, 0x47,
	0x69, 0xd5, 0x2c, 0xda, 0xf1, 0xd8, 0xac, 0x79, 0x1c, 0x80, 0x8b, 0xab, 0x98, 0x2e, 0xc7, 0x2d,
	0x23, 0xab, 0xc1, 0x8e, 0x73, 0xb7, 0xe6, 0xfc, 0x19, 0x5a, 0x2f, 0x02, 0xf9, 0xde, 0x97, 0x6f,
	0x58, 0x1b, 0x7f, 0xb1, 0x36, 0x6b, 0xac, 0x33, 0x38, 0xdc, 0xbe, 0x73, 0x5f, 0x24, 0xe4, 0x14,
	0x5a, 0x4a, 0x47, 0x53, 0xf7, 0xa6, 0xbd, 0x89, 0xf9, 0x24, 0x65, 0x29, 0xd4, 0x8d, 0xe0, 0x4e,
	0x47, 0xcb, 0x0a, 0x59, 0x09, 0x4c, 0x35, 0x22, 0x9a, 0x94, 0x81, 0x29, 0x38, 0x4b, 0xb6, 0x02,
	0x8d, 0x6a, 0xe6, 0xd7, 0xf0, 0xbf, 0x9c, 0xb7, 0x46, 0x02, 0xe8, 0x53, 0x11, 0x2d, 0x59, 0x9a,
	0x62, 0x12, 0xb1, 0x42, 0x6a, 0x9a, 0x4e, 0xd8, 0xa3, 0x62, 0xae, 0x6b, 0x4f, 0x85, 0x9c, 0x7e,
	0x3b, 0xd0, 0x55, 0x26, 0xe6, 0xca, 0x0e, 0x99, 0x82, 0x6b, 0x0e, 0xc7, 0xd6, 0x5f, 0x75, 0x69,
	0xfc, 0xc1, 0x6e, 0xd1, 0xaa, 0xdc, 0x42, 0xa7, 0x8c, 0x80, 0x0c, 0xed, 0x8d, 0xda, 0xdf, 0xfb,
	0xa3, 0x5f, 0x75, 0x3b, 0x7c, 0x03, 0x9e, 0x31, 0x4d, 0x2a, 0xe4, 0xdb, 0x0c, 0xfc, 0x93, 0x5a,
	0xd5, 0x8c, 0xdd, 0xb7, 0x5f, 0xcd, 0x5e, 0xbf, 0x79, 0x7a, 0xcb, 0xaf, 0x7e, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x54, 0x2a, 0xc1, 0xe7, 0xfa, 0x02, 0x00, 0x00,
}
